### ISSUE TITLE
идеи навскидку - пока не забыл

### ISSUE THREAD

**Issue by ghost** [KrapivinAndrey/ChocoInstall1c#1]
Использовать oscript с генерацией по следующему сценарию

* пусть будет некий каталог в формате distr/<v8version>/setup.zip
* для каждого каталога генерируем nuspec на основе шаблона меняя только версию через СтрЗаменить()
* В исходной статье на Инфостарте - зменить Apache на Nginx (можно через docker). целый Apache здесь не нужен
* Применить docker run nginx или oscript.web ;-) быстрей будет

**Comment by KrapivinAndrey** [comment]
это "некоторый скрипт" был. Я бы сдох все платформы от 8.2.15 до 8.3.12 обрабатывать. Найти пока не могу куда дел.

Apache просто для примера, у нас уже был поднят. Подойдет любой веб-сервер для публикации каталога.
Но! Если захочется публиковать пакеты choco не по шаре, а через веб - придется ставить IIS. Только с ним работает.

**Comment by KrapivinAndrey** [comment]
Вот если бы был скрипт на скачивание платформы, тогда можно полностью автоматизировать процесс.... Но там какой-то ахтунг с получение ссылки, на конфигурации нормальные ссылки, на платформу ерунда какая-то.

**Comment by KrapivinAndrey** [comment]
@allustin Привет. Неожиданно пришлось вернуться к этой теме.

Есть следующая идея.
1. Скрипт сборки нугет-пакетов прямо с ПЛАТФОРМОЙ внутри.
2. Благодаря докеру теперь можно поднять ChocoServer
https://github.com/takhyon/docker-chocolatey.server

Буду держать в курсе

**Comment by ghost** [comment]
@KrapivinAndrey мне также пришлось вернутся. Для docker + windows - буквально в пятницу.

**Comment by KrapivinAndrey** [comment]
@allustin Привет. Поэксперементировали. Оказывается нугет больше 500 MB собрать нельзя. Поэтому платформу упаковать не получилось.
Но написали скрипт на py, который собирает нугет с ссылкой на оф. сайт. Попробую переписать его на oscript в проект. Будет жить вот здесь https://github.com/KrapivinAndrey/chocolate-factory
